### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by stjernegard** [IFTTT/ConnectSDK-iOS#280]
Our app supports dark mode, so the connect button looks a little off as it is now with dark on dark.

It seems dark mode support is partially implemented already (https://github.com/IFTTT/ConnectSDK-iOS/blob/master/IFTTT%20SDK/ConnectButton%2BStyle.swift#L37-L39).

**Comment by ssathy2** [comment]
Hi @stjernegard, this is something on our roadmap but I don't have a definitive timeline in terms of when this change will be implemented. Once we have a better idea of the timeline going forward, I'll comment on this issue.

Thanks!
