### ISSUE TITLE
Unable to compile using Xcode 13/Swift 5.5

### ISSUE THREAD

**Issue by vrutberg** [IFTTT/ConnectSDK-iOS#282]
Hi,

I noticed that we are unable to build this SDK using Xcode 13/Swift 5.5. It seems like annotating enum cases with associated values with '@available' generates a compiler error. I'm not sure if this is a bug or a feature of Xcode 13/Swift 5.5.

There is a Swift issue reported on this behavior, however it doesn't seem to have received much attention since April: https://bugs.swift.org/browse/SR-14539.

Do you have any news or more insight to share on this?

Regards,
Viktor

**Comment by vrutberg** [comment]
Hi,

In Xcode 13b3 this was added to the release notes:

>The compiler used to erroneously accept @available annotations on enum cases with associated values that were newer than the deployment target. (80238318)
>
>For example:
>
>public struct Crayon {}
>
>public enum Pen {
>    case pencil
>
>    @available(macOS 12, *)
>    case crayton(Crayon)
>}
>
>While this worked in some cases, there was no way for the Swift runtime to perform the requisite dynamic layout needed in general, so this could cause crashes at runtime. The compiler now rejects such availability newer than the deployment target on enum cases.

**Comment by ssathy2** [comment]
Hi @vrutberg, this is something that the team is aware of and is working on. This will require an SDK update. Thanks!

**Comment by ssathy2** [comment]
This should now be resolved in 2.7.0 beta1.
